function generateVoxelShaders() {
    var id = shell.desktop.window;
    var shaderText = "";

    ui.fillListFiles(id, "props/", "/", "", 0); // Главный список директорий
    for (var i = 0; i < ui.getFileListCount(id, 0); i++) {
        if (ui.getFileFromList(id, 0, i) === "" || ui.getFileFromList(id, 0, i) === "." || ui.getFileFromList(id, 0, i) === "..") continue;
        ui.fillListFiles(id, "props/" + ui.getFileFromList(id, 0, i), "", "", 1); // Список текстур
        shaderText += "// Automatic shader file for " + "props/" + ui.getFileFromList(id, 0, i) + " generated by noire.dev\n";
        for (var j = 0; j < ui.getFileListCount(id, 1); j++) {
            var folderName = ui.getFileFromList(id, 0, i);
            var textureName = ui.getFileFromList(id, 1, j);
            var textureNameWithoutExt = textureName.slice(0, -4);
            var dotIndex = textureName.lastIndexOf('.');
            var baseName = (dotIndex !== -1) ? textureName.substring(0, dotIndex) : textureName;
            shaderText += "props/" + folderName + "/" + baseName + "\n";
            shaderText += "{\n";
            //shaderText += "    nofilter\n";
            shaderText += "    {\n";
            shaderText += "        map " + "props/" + folderName + "/" + textureName + "\n";
            shaderText += "        rgbGen lightingDiffuse" + "\n";
            shaderText += "    }\n";
            shaderText += "}\n";
            shaderText += "\n";
        }
        file.save("scripts/props-" + folderName + ".shader", shaderText);
        shaderText = "";
    }
}

generateVoxelShaders();